### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by electron0zero** [llSourcell/antivirus_demo#2]
```
Traceback (most recent call last):
  File "checkpe.py", line 185, in <module>
    'r').read()
TypeError: a bytes-like object is required, not 'str'
```

**Comment by electron0zero** [comment]
```
Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

python version

**Comment by philkuz** [comment]
this is a pretty simple fix I found on [StackOverflow](http://stackoverflow.com/questions/13906623/using-pickle-dump-typeerror-must-be-str-not-bytes)

simply change 
`open('classifier/features.pkl', 'w').write(pickle.dumps(features))`
to `open('classifier/features.pkl', 'wb').write(pickle.dumps(features))`

**Comment by llSourcell** [comment]
hmmm. did you find a fix? if so, make a PR and i'll merge

**Comment by irshadirfan** [comment]
hey u need to open in binary 
so change it to "wb"
[ open('classifier/features.pkl', 'wb').write(pickle.dumps(features)) ]
